# vi: set ft=ruby :

MACHINES = {
  :web => {
        :box_name => "centos/7",
        :ip_addr => '172.16.0.2'
  },
  :log => {
    :box_name => "centos/7",
    :ip_addr => '172.16.0.1'
  }
}

Vagrant.configure("2") do |config|


  config.vm.define "web" do |web|
    web.vm.hostname = "web"
    web.vm.provision "shell", path:
      "web.sh"
  end

  config.vm.define "log" do |log|
    log.vm.hostname = "log"
    log.vm.provision "shell", path:
      "log.sh"
  end

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "200"]
          end

          box.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
            sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            systemctl restart sshd
          SHELL

      end
  end
end
