[ns01]
127.0.0.1

[ns02]
192.168.50.11

[client1]
192.168.50.15

[client2]
192.168.50.25

[dnssrv:children]
ns01
ns02

[clients:children]
client1
client2

[dnssrv:vars]
ansible_user = vagrant
ansible_ssh_private_keyfile = /home/vagrant/.ssh

[clients:vars]
ansible_user = vagrant
ansible_ssh_private_keyfile = /home/vagrant/.ssh
