# -*- mode: ruby -*-
# vi: set ft=ruby :

MACHINES = {
  :nginx => {
        :box_name => "centos/7",
        :ip_addr => '172.16.0.2'
  },
  :master => {
    :box_name => "centos/7",
    :ip_addr => '172.16.0.1'
  }
}

Vagrant.configure("2") do |config|

   
  config.vm.define "nginx" do |nginx|
    nginx.vm.hostname = "nginx"
    nginx.vm.provision "shell", path:
      "ngxstrconf.sh"
  end

  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.provision "shell", path:
      "ansstrconf.sh"
  end

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "200"]
          end  

          box.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
            sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            systemctl restart sshd
          SHELL

      end
  end
end
