---
- hosts: all
  vars:
    kernel_ver: 5.6.8
  become: true
  tasks:
  - name: Install packages
    yum: 
      name:
        - "@Development tools"
        - wget
        - ncurses-devel
        - bison
        - flex
        - bc
        - openssl-devel
        - elfutils-libelf-devel
      state: present
      update_cache: yes

  - name: Download kernel
    get_url:
      url: https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.6.8.tar.xz
      dest: /tmp/linux-{{ kernel_ver }}.tar.xz

  - name: Untar kernel
    shell: tar -Jxvf linux-{{ kernel_ver }}.tar.xz
    args:
      chdir: /tmp/

  - name: Copy config
    copy:
      src: .config
      dest: /tmp/linux-{{ kernel_ver }}/.config

  - name: Make kernel
    shell: "{{ item }}"
    with_items:
    - make -j 2
    - make modules
    - make modules_install
    - make install
    args:
      chdir: /tmp/linux-{{ kernel_ver }}/

  - name: Configure grub
    shell: "{{ item }}"
    with_items:
    - grub2-mkconfig -o /boot/grub2/grub.cfg
    - grubby --set-default /boot/vmlinuz-5.6.8
    

