servers=[
  {
    :hostname => "kernel-make-1",
    :ip => "10.10.10.10",
    :box => "centos7.7_5.6.10",
    :ram => 4096,
    :cpu => 4,
  }
]

Vagrant.configure(2) do |config|
    servers.each do |machine|
        if Vagrant.has_plugin?("vagrant-vbguest")
            config.vbguest.auto_update = true
          end
          config.vm.synced_folder "~/gitz/manual_kernel_update/.shared/", "/shared", type: "virtualbox", disabled: false
          ssh_pub_key = File.readlines("#{Dir.home}/.ssh/appuser.pub").first.strip
          config.vm.provision 'shell', inline: "echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys", privileged: false
          

        config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box]
            node.vm.hostname = machine[:hostname]
            node.vm.network "private_network", ip: machine[:ip]
            node.vm.provider "virtualbox" do |vb|
                vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
                vb.customize ["modifyvm", :id, "--cpus", machine[:cpu]]
            end
        end
    end
end